# values.yaml

replicaCount: 1

image:
  repository: salmanidrisi/pharmacy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

# Add any additional configuration parameters here

serviceAccount:
  create: false

ingress:
  enabled: true

autoscaling:
  enabled: false
